# -*- coding: utf-8 -*-
"""SPAM CLASSIFIER 1A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqW_3Bfow2Bzt57GFT7ldWu94RPo-GfD

# CAPSTONE PROJECT GROUP 3 - SPAM EMAIL CLASSIFIER

## 1. IMPORTING THE NECESSARY LIBRARIES
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
import pickle
import re
import string
import joblib
import warnings
warnings.filterwarnings('ignore')

"""### 1.1 IMPORTING THE DATASET FROM MY DOWNLOADED FILES"""

df = pd.read_csv('/content/spam.csv', encoding='latin1')

"""## 2. VIEWING THE PROPERTIES OF THE DATASET

### 2.1 Vieing Shape of Dataframe
This shows that they are 5 columns and 5,572 rows in the data set.
"""

df.shape

"""### 2.2. Dataset information;
This gives a summary of the information contained in the dataset as it concerns the number of entries, rows/columns, datatype, missing values etc
"""

df.info()

print(f"\nColumn names: {df.columns.tolist()}")

"""### 2.3 Dataset Preview - from head or tail:
This displays a range of the set, either from the top or bottom entries.
"""

df.head(20)

df.tail()

"""### 2.4 Describing the dataframe:
This gives the statistical analysis of the dataset where necessary.
"""

df.describe()

df.describe().T

"""## 3. DATA PREPROCESSING AND CLEANING

### 3.1 Dropping irrelevant columns
"""

df = df.drop(columns=['Unnamed: 2',	'Unnamed: 3',	'Unnamed: 4',])

"""### 3.2\ Renaming v1 and v2 to Label and text respectively"""

df=df.rename(columns={"v1":"Label","v2":"text"})

"""### 3.3 Checking for missing values"""

df.isnull().sum()

"""### 3.4 Checking for duplicates and removing duplicates"""

duplicates_before = len(df)
df = df.drop_duplicates()
duplicates_after = len(df)
print(f"\nDuplicates removed: {duplicates_before - duplicates_after}")

# Check class distribution
print(f"\nClass distribution (before cleaning):")
print(df['Label'].value_counts())
print(f"Class percentage:")
print(df['Label'].value_counts(normalize=True) * 100)

# Remove missing values
df = df.dropna()
print(f"Dataset shape after cleaning: {df.shape}")

# Convert labels to numeric (ham=0, spam=1)
df['Label'] = (df['Label'] == 'spam').astype(int)

"""### Text preprocessing - remove URLs, emails, and special characters"""

def clean_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    # Remove special characters but keep spaces
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

print("\nCleaning text...")
df['text'] = df['text'].apply(clean_text)

# Remove empty texts
df = df[df['text'].str.len() > 0]
print(f"Dataset shape after text cleaning: {df.shape}")

"""## 4. Feature Extraction"""

# Create vectorizer with optimized parameters
vectorizer = TfidfVectorizer(
    max_features=3000,           # Limit features for efficiency
    min_df=2,                    # Minimum document frequency
    max_df=0.9,                  # Maximum document frequency
    ngram_range=(1, 2),          # Unigrams and bigrams
    stop_words='english',
    lowercase=True
)

X = vectorizer.fit_transform(df['text'])
y = df['Label']

print(f"Feature matrix shape: {X.shape}")
print(f"Number of features: {X.shape[1]}")
print(f"Sparsity: {1.0 - (X.nnz / (X.shape[0] * X.shape[1])):.2%}")

"""## 5. Test - Train Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training set size: {X_train.shape[0]} ({X_train.shape[0]/len(y)*100:.1f}%)")
print(f"Test set size: {X_test.shape[0]} ({X_test.shape[0]/len(y)*100:.1f}%)")
print(f"Training spam ratio: {y_train.sum()/len(y_train)*100:.1f}%")
print(f"Test spam ratio: {y_test.sum()/len(y_test)*100:.1f}%")

clf = RandomForestClassifier(n_jobs=-1)
clf.fit(X_train, y_train)

plt.figure(figsize=(4, 2))
sns.countplot(x='Label', data=df)
plt.title('Distribution of Emails: Spam vs Ham')
plt.xlabel('Label')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1], labels=['Ham', 'Spam'])
plt.show()

"""### 6. Train Multiple Models"""

# Dictionary to store models and their results
models = {}
results = {}

# Model 1: Naive Bayes
print("\n  Training Naive Bayes...")
nb_model = MultinomialNB(alpha=0.1)
nb_model.fit(X_train, y_train)
nb_pred = nb_model.predict(X_test)
nb_pred_proba = nb_model.predict_proba(X_test)

models['Naive Bayes'] = nb_model
results['Naive Bayes'] = {
    'predictions': nb_pred,
    'probabilities': nb_pred_proba
}

# Model 2: Logistic Regression
print("  Training Logistic Regression...")
lr_model = LogisticRegression(max_iter=1000, random_state=42, C=0.5)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
lr_pred_proba = lr_model.predict_proba(X_test)

models['Logistic Regression'] = lr_model
results['Logistic Regression'] = {
    'predictions': lr_pred,
    'probabilities': lr_pred_proba
}

# Model 3: Support Vector Machine
print("  Training Support Vector Machine...")
svm_model = SVC(kernel='linear', probability=True, random_state=42, C=1.0)
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
svm_pred_proba = svm_model.predict_proba(X_test)

models['SVM'] = svm_model
results['SVM'] = {
    'predictions': svm_pred,
    'probabilities': svm_pred_proba
}

"""### 7. Evaluating Models"""

print("\n" + "="*70)

eval_results = {}

for model_name, model_obj in models.items():
    y_pred = results[model_name]['predictions']

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)

    eval_results[model_name] = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

    print(f"\n{model_name}:")
    print(f"  Accuracy:  {accuracy:.4f} ({accuracy*100:.2f}%)")
    print(f"  Precision: {precision:.4f} ({precision*100:.2f}%)")
    print(f"  Recall:    {recall:.4f} ({recall*100:.2f}%)")
    print(f"  F1 Score:  {f1:.4f}")

"""# 8. Choosing the most optimal model

---


"""

best_model_name = max(eval_results, key=lambda x: eval_results[x]['f1'])
best_model = models[best_model_name]
best_f1 = eval_results[best_model_name]['f1']

print(f"\n✓ Best Model: {best_model_name} (F1 Score: {best_f1:.4f})")

"""### 9. Confusion Matrix & Detailed Report"""

y_pred_best = results[best_model_name]['predictions']
cm = confusion_matrix(y_test, y_pred_best)

print(f"\nConfusion Matrix:")
print(cm)
print(f"\nTrue Negatives: {cm[0][0]}")
print(f"False Positives: {cm[0][1]}")
print(f"False Negatives: {cm[1][0]}")
print(f"True Positives: {cm[1][1]}")

print(f"\nClassification Report:")
print(classification_report(y_test, y_pred_best, target_names=['Ham', 'Spam']))

"""### 10. Testing on Examples"""

test_examples = [
    ("FDFVOJ[S[OJFO[AESTABFOD]K       FD0FJ=ZD-]KALDS[C", "Gibberish"),
    ("Click here to win $1000 prize now!", "Spam"),
    ("Congratulations you won a lottery", "Spam"),
    ("Hi, how are you doing today?", "Ham"),
    ("Call me ASAP!", "Ham"),
    ("FREE money click here", "Spam"),
    ("Meeting at 3pm tomorrow", "Ham"),
    ("You have inherited 1 million dollars", "Spam"),
]

print("\nSample Predictions:")
for text, expected in test_examples:
    # Clean the text using same preprocessing
    cleaned_text = clean_text(text)
    transformed = vectorizer.transform([cleaned_text])

    pred = best_model.predict(transformed)[0]
    proba = best_model.predict_proba(transformed)[0]

    predicted_label = "SPAM" if pred == 1 else "HAM"
    confidence = proba[pred] * 100

    status = "✓" if (pred == 1 and expected == "Spam") or (pred == 0 and expected == "Ham") else "✗"

    print(f"\n{status} Text: '{text}'")
    print(f"   Expected: {expected} | Predicted: {predicted_label} ({confidence:.1f}% confidence)")

"""### 11. Save Data"""

spam_classifier = {
    'model_type': best_model_name,
    'accuracy': eval_results[best_model_name]['accuracy'],
    'precision': eval_results[best_model_name]['precision'],
    'recall': eval_results[best_model_name]['recall'],
    'f1_score': eval_results[best_model_name]['f1'],
    'features': X.shape[1],
    'classes': ['Ham', 'Spam']
}

# Save the metadata dictionary
spam_classifier_metadata_filename = 'spam_classifier_metadata.pkl'
joblib.dump(spam_classifier, spam_classifier_metadata_filename)

# Save the best model
model_filename = 'best_spam_model.pkl'
joblib.dump(best_model, model_filename)

# Save the vectorizer
vectorizer_filename = 'tfidf_vectorizer.pkl'
joblib.dump(vectorizer, vectorizer_filename)

print(f"\n✓ Spam classifier metadata saved: {spam_classifier_metadata_filename}")
print(f"✓ Best model saved: {model_filename}")
print(f"✓ TF-IDF vectorizer saved: {vectorizer_filename}")

print("\n" + "="*70)
print("TRAINING COMPLETE!")
print("="*70)
print("\n📋 Summary:")
print(f"  • Best Model: {best_model_name}")
print(f"  • Test Accuracy: {eval_results[best_model_name]['accuracy']*100:.2f}%")
print(f"  • F1 Score: {eval_results[best_model_name]['f1']:.4f}")
print(f"\n📁 Files to download:")
print(f"  1. {model_filename}")
print(f"  2. {vectorizer_filename}")
print(f"  3. {spam_classifier_metadata_filename}")

!pip install streamlit
import streamlit as st

model = joblib.load("best_spam_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

st.title("🔒 Spam Classifier")

email_text = st.text_area("Enter Email Text", placeholder="Paste your email here...")

if st.button("Classify Email"):
    if email_text.strip() == "":
        st.warning("⚠️ Please enter email text to classify.")
    else:
        transformed = vectorizer.transform([email_text])
        prediction = model.predict(transformed)
        confidence = model.predict_proba(transformed).max()

        if prediction[0] == 1:
            st.error(f"🚨 **Spam Detected** (Confidence: {confidence:.2%})")
        else:
            st.success(f"✅ **Legitimate Email** (Confidence: {confidence:.2%})")

        # Show top spam indicators
        st.markdown("---")
        st.info(f"Classification Confidence: {confidence:.2%}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# 
# # Load the trained model and vectorizer
# model = joblib.load("best_spam_model.pkl")
# vectorizer = joblib.load("tfidf_vectorizer.pkl")
# 
# # Streamlit app title
# st.title("🔒 Spam Classifier")
# 
# # Text area for user input
# email_text = st.text_area("Enter Email Text", placeholder="Paste your email here...")
# 
# # Classify button
# if st.button("Classify Email"):
#     if email_text.strip() == "":
#         st.warning("⚠️ Please enter email text to classify.")
#     else:
#         # Clean and transform the input text
#         # Assuming clean_text function is available or defined within app.py if needed.
#         # For this example, let's assume it's part of the pre-processing chain handled by the vectorizer or model.
#         # If clean_text was a separate function, it would need to be included here.
# 
#         # For now, directly transform. In a real deployment, ensure clean_text is applied.
#         transformed = vectorizer.transform([email_text])
# 
#         # Make prediction
#         prediction = model.predict(transformed)
#         confidence = model.predict_proba(transformed).max()
# 
#         # Display results
#         if prediction[0] == 1:
#             st.error(f"🚨 **Spam Detected** (Confidence: {confidence:.2%})")
#         else:
#             st.success(f"✅ **Legitimate Email** (Confidence: {confidence:.2%})")
# 
#         st.markdown("---")
#         st.info(f"Classification Confidence: {confidence:.2%}")
#

from google.colab import files

files_to_download = [
    'best_spam_model.pkl',
    'tfidf_vectorizer.pkl',
    'spam_classifier_metadata.pkl',
    'app.py'
]

for file_name in files_to_download:
    try:
        files.download(file_name)
    except FileNotFoundError:
        print(f"Warning: {file_name} not found. Please ensure it was created correctly.")
    except Exception as e:
        print(f"Error downloading {file_name}: {e}")



"""###

##
"""